default: &defaults
  parallelism: 1
  working_directory: ~/LocustDemo

performance_tests: &performance_tests
  run:
    name: Running tests
    command: |
      chmod +x test_automation.sh
      ./test_automation.sh

version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: "Switch to Python v3.7"
          command: |
            pyenv versions
            pyenv global 3.7.0
      - *performance_tests
  run_performance_tests:
    <<: *defaults
    # Use `machine` executor because the Docker executor cannot mount volumes
    machine: true
    steps:
      - checkout
      - *performance_tests

#orbs:
#  python: circleci/python@1.0.0

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      #- run_performance_tests
