default: &defaults
  parallelism: 1
  working_directory: ~/LocustDemo

performance_tests: &performance_tests
  run:
    name: Running tests
    command: |
      chmod +x test_automation.sh
      ./test_automation.sh

version: 2
jobs:
  run_performance_tests:
    <<: *defaults
    # Use `machine` executor because the Docker executor cannot mount volumes
    machine: true
    steps:
      - checkout
      - *performance_tests

orbs:
  python: circleci/python@1.0.0

workflows:
  version: 2
  build-and-test:
    jobs:
      - run_performance_tests
